### ISSUE TITLE
Full App Tests and Server Start

### ISSUE THREAD

**Issue by remygendron** [DispatchMe/meteor-mocha#1]
Hello there,

I'm using dispatch:mocha to run full-app tests (and server unit tests) as I currently get phantomjs errors with dispatch:mocha-phantomjs.

I run my tests with:

meteor test --full-app --settings settings-ci.json --once --driver-package dispatch:mocha

My challenge is to wait for the server to fully initialize before the tests are launched. For instance, I use percolate:migrations to manage my schema and my migration scripts don't have time to finish before the full-app tests start running. I use Meteor.startup() to trigger my migrations as per this package documentation.

Still just a few weeks into Meteor. What would you recommend as a best practice, in a CI environment, to have the test suite wait on full server initialization before launching?

Many thanks for your contribution to Meteor! :-)

Remy

**Comment by aldeed** [comment]
I'm not sure that in general it would be best practice to have migrations running for tests, even full app/end-to-end tests. Can you wrap your migrations in `if (!Meteor.isAppTest)` so that they don't run, and then insert whatever data you need for your tests in a mocha `before` hook?

**Comment by aldeed** [comment]
Otherwise you can have an async `before` hook that checks for the necessary data every second using setInterval and doesn't call `done` until it's there.

**Comment by remygendron** [comment]
Eric, I like your second suggestion. I was not aware that in the before
hook, there was a 'done' api...

As for database migrations, they need to run as part of the continuous
integration pipeline. Those migrations contain more than data inserts, they
also contain schema changes. We're doing continuous delivery and those
scripts will be run in production as part of the app being deployed. We
need to test those scripts as much as we need to test the new code.

Thank you for your suggestions!

On Wed, May 11, 2016 at 6:23 PM Eric Dobbertin <notifications@github.com>
wrote:

> Otherwise you can have an async before hook that checks for the necessary
> data every second using setInterval and doesn't call done until it's
> there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DispatchMe/meteor-mocha/issues/1#issuecomment-218608317>
>
-- 
Rémy Gendron
Ingeno / Be the Revolution

418 809-8585
remy.gendron@ingeno.ca
remy.gendron (Skype)
http://ingeno.ca

**Comment by aldeed** [comment]
OK, yeah it all depends on what your process is.
