### ISSUE TITLE
getting `select: Invalid argument` when attempting to run it with phantom js

### ISSUE THREAD

**Issue by Pushplaybang** [DispatchMe/meteor-mocha#18]
Hey There

The server side tests run fine, but with the following command I get this error.  My test command is:

```sh
cd app/ && TEST_BROWSER_DRIVER=phantomjs meteor test --once --driver-package dispatch:mocha
```

Any help would be great.  Thanks.

**Comment by Pushplaybang** [comment]
note that I have installed phantomjs-prebuilt as described in the readme

**Comment by jaskinn** [comment]
I am experiencing this as well.

**Comment by aldeed** [comment]
Duplicate of https://github.com/DispatchMe/meteor-mocha-phantomjs/issues/33

Basically you may or may not see this sometimes when running, and it has something to do with memory and/or timing and/or limits on open files. But it's a PhantomJS issue that they most likely won't fix anytime soon, so the best choice is probably to try using one of the other supported browsers.
