### ISSUE TITLE
mocha vs mocha-phantomjs

### ISSUE THREAD

**Issue by macsj200** [DispatchMe/meteor-mocha#22]
Hello, I'm working on getting my tests running on Travis CI, and I'm very confused about the relationship between dispatch:mocha and dispatch:mocha-phantomjs.

Could someone explain what these two (one?) packages do please?

Thanks.

**Comment by aldeed** [comment]
Use `dispatch:mocha`. It now can do what `dispatch:mocha-phantomjs` does.
