### ISSUE TITLE
Testing restivus endpoints with mocha

### ISSUE THREAD

**Issue by keyscores** [DispatchMe/meteor-mocha#3]
I'm trying to set up some test cases for my Restivus endpoints, while using dispatch:mocha package for the test runner.

Inside the test runner, I'm using the popular node Request library to get responses from the API. However I'm unexpectedly getting the whole meteor app payload, and not my specified response.

The test runner is run as per the meteor guide practices:

> meteor test --driver-package dispatch:mocha --port 3000 

describe('API', function (  ) {
  it('sanity test', function (done) {
          request({
            method: "GET",
            url: 'http://localhost:3000/api/anything'
          }, function( err, res ){
              console.log("callback url response: ", res);
              done();
          });
    });
  });
})
The result is a very large payload with js and css. Any thoughts on setting up tests for endpoints?

Same issue as : https://github.com/kahmali/meteor-restivus/issues/223

**Comment by keyscores** [comment]
For others looking for a solution practicalmeteor:mocha is the test runner that worked for me. You need to do the 'full app' test method. That is, name the tests *.app-test.js

**Comment by aldeed** [comment]
You do need to add `--full-app` so that the endpoints are created, but it should work with any test driver package, including this one, as long as you do that.
