### ISSUE TITLE
'MOCHA_GREP' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by vipul08** [DispatchMe/meteor-mocha#32]
Hi,

While running the meteor test. I got one error.
command: MOCHA_GREP="WishList" meteor test --once --driver-package dispatch:mocha

Please look into it

**Comment by aldeed** [comment]
Hi @vipul08. That's an OS error, so not related to this package. Double check that you're setting the environment variable in the proper way for whatever operating system you use.
