### ISSUE TITLE
Add ENV to run server-client tests in series

### ISSUE THREAD

**Issue by aldeed** [DispatchMe/meteor-mocha#6]
To keep things quick, client tests are started at the same time as server tests. We can add something like `TEST_SERIES=1` env variable for people who have bad tests that cause side effects.

**Comment by keyscores** [comment]
How would you propose to control the flow? I'm guessing there are only two stage to consider, browser and client. Could there be more? For example an "acceptance" stage?

**Comment by aldeed** [comment]
Yeah, I guess series as default would be fine but it could be quite a bit slower in some apps.

This shouldn't be too hard to implement: Pull the `startBrowser` call into a separate function, and then call that function either in `start` or in `exitIfDone`, depending on whether the ENV variable is set.

**Comment by keyscores** [comment]
Thanks for the merge. Can close now.
