### ISSUE TITLE
Selectively run or ignore tests with --grep and --invert

### ISSUE THREAD

**Issue by lpgeiger** [DispatchMe/meteor-mocha#7]
I'm thinking this is in the domain of practicalmeteor:mocha-core. I'm not familiar enough with internals of mocha. Any thoughts on where to start. https://github.com/DispatchMe/meteor-mocha/issues/8

**Comment by aldeed** [comment]
It doesn't matter to me much whether we do this in mocha-core or in this package. It could be done by passing the options [here](https://github.com/practicalmeteor/meteor-mocha-core/blob/practicalmeteor/server.js#L109-L112) in the core package or by calling `mocha.setup(options)` before `mocha.run` in both the server and client files in this pkg.
